# Generated by Django 3.0.7 on 2020-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoteUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='Cname',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='Image',
            new_name='image',
        ),
    ]
