# Generated by Django 3.0.7 on 2020-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoteUser', '0002_auto_20200718_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='count',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
